/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

/**
 *
 * @author Harsh Kakasaniya
 */
public class After_Cust_Sign_In_OR_Up extends javax.swing.JFrame {

    /**
     * Creates new form After_Cust_Sign_In_OR_Up
     */
    public After_Cust_Sign_In_OR_Up() {
        initComponents();
        setSize(970,880);
        setTitle("Order Now !!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Rest_DropDown_After_Sign_IN_OR_UP = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Menu_Items_After_Sign_IN_OR_UP = new javax.swing.JComboBox();
        ConfirmOrder = new javax.swing.JButton();
        Item_Quantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Order Fast, Get Fresh");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 0, 870, 150);

        Rest_DropDown_After_Sign_IN_OR_UP.setBackground(new java.awt.Color(255, 153, 102));
        Rest_DropDown_After_Sign_IN_OR_UP.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Rest_DropDown_After_Sign_IN_OR_UP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Need to set based on city" }));
        Rest_DropDown_After_Sign_IN_OR_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_DropDown_After_Sign_IN_OR_UPActionPerformed(evt);
            }
        });
        jPanel1.add(Rest_DropDown_After_Sign_IN_OR_UP);
        Rest_DropDown_After_Sign_IN_OR_UP.setBounds(30, 190, 380, 40);

        jLabel13.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel13.setText("Select restaurant");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(100, 140, 260, 50);

        jLabel14.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel14.setText("Quantity");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 240, 130, 60);

        Menu_Items_After_Sign_IN_OR_UP.setBackground(new java.awt.Color(255, 153, 102));
        Menu_Items_After_Sign_IN_OR_UP.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Menu_Items_After_Sign_IN_OR_UP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Need to set based on Rest" }));
        Menu_Items_After_Sign_IN_OR_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Items_After_Sign_IN_OR_UPActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Items_After_Sign_IN_OR_UP);
        Menu_Items_After_Sign_IN_OR_UP.setBounds(560, 190, 370, 40);

        ConfirmOrder.setBackground(new java.awt.Color(255, 153, 102));
        ConfirmOrder.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ConfirmOrder.setText("Confirm Order");
        ConfirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmOrderActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmOrder);
        ConfirmOrder.setBounds(690, 730, 220, 70);

        Item_Quantity.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jPanel1.add(Item_Quantity);
        Item_Quantity.setBounds(600, 250, 60, 40);

        Cart.setColumns(20);
        Cart.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Cart.setRows(5);
        jScrollPane1.setViewportView(Cart);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 890, 360);

        jLabel15.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel15.setText("Menu");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 180, 80, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rest_DropDown_After_Sign_IN_OR_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_DropDown_After_Sign_IN_OR_UPActionPerformed
        // TODO add your handling code here:
        // ADD ITEMS BASED ON CITY
    }//GEN-LAST:event_Rest_DropDown_After_Sign_IN_OR_UPActionPerformed

    private void Menu_Items_After_Sign_IN_OR_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Items_After_Sign_IN_OR_UPActionPerformed
        // TODO add your handling code here:
        // ADD ITEMS BASED ON RESTAURANT SELECTED
    }//GEN-LAST:event_Menu_Items_After_Sign_IN_OR_UPActionPerformed

    private void ConfirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmOrderActionPerformed
        // TODO add your handling code here:
        Cust_SignUp mf = new Cust_SignUp();
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_ConfirmOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(After_Cust_Sign_In_OR_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(After_Cust_Sign_In_OR_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(After_Cust_Sign_In_OR_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(After_Cust_Sign_In_OR_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new After_Cust_Sign_In_OR_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cart;
    private javax.swing.JButton ConfirmOrder;
    private javax.swing.JSpinner Item_Quantity;
    private javax.swing.JComboBox Menu_Items_After_Sign_IN_OR_UP;
    private javax.swing.JComboBox Rest_DropDown_After_Sign_IN_OR_UP;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
