/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.*;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Harsh Kakasaniya
 */
public class Cust_SignUp extends javax.swing.JFrame {

    Connection conn = null;
    CallableStatement stmt = null;
    ResultSet rs = null;
    
    int cusId = 0;
    
    public Cust_SignUp() {
        initComponents();
        setSize(550,870);
        setTitle("Join us to get your Food Fast and Fresh !!!");
    }
    
    public Cust_SignUp(Connection conn) {
        initComponents();
        setSize(550,870);
        setTitle("Join us to get your Food Fast and Fresh !!!");
        this.conn = conn;
        
        fillStates();
    }
    
    void fillStates(){
        try {
            stmt = conn.prepareCall("{call statesList(?)}");
            stmt.registerOutParameter(1, OracleTypes.CURSOR);
            stmt.execute();
            
            rs = (ResultSet) stmt.getObject(1);
            while(rs.next()){
                C_State.addItem(rs.getString("s_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cust_SignIn = new javax.swing.JButton();
        Cust_SignUp_Info_Page = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        C_FName = new javax.swing.JTextField();
        C_LName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        C_Email = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        C_PhoneNo = new javax.swing.JTextField();
        C_Street = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        C_Area = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        C_State = new javax.swing.JComboBox<>();
        C_City = new javax.swing.JComboBox<>();
        C_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Fast& Fresh");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 40, 430, 150);

        jLabel3.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 102));
        jLabel3.setText("Get your Food");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, -30, 430, 150);

        jLabel13.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel13.setText("Already a Foodoholic ??");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 740, 320, 50);

        Cust_SignIn.setBackground(new java.awt.Color(255, 153, 102));
        Cust_SignIn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Cust_SignIn.setText("Sign In");
        Cust_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_SignInActionPerformed(evt);
            }
        });
        jPanel1.add(Cust_SignIn);
        Cust_SignIn.setBounds(360, 730, 130, 70);

        Cust_SignUp_Info_Page.setBackground(new java.awt.Color(255, 153, 102));
        Cust_SignUp_Info_Page.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Cust_SignUp_Info_Page.setText("Sign Up");
        Cust_SignUp_Info_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_SignUp_Info_PageActionPerformed(evt);
            }
        });
        jPanel1.add(Cust_SignUp_Info_Page);
        Cust_SignUp_Info_Page.setBounds(370, 620, 130, 70);

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel8.setText("Last Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 200, 160, 60);

        C_FName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_FName);
        C_FName.setBounds(180, 160, 320, 40);

        C_LName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_LName);
        C_LName.setBounds(180, 210, 320, 40);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel9.setText("First Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 150, 170, 60);

        jLabel12.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 250, 100, 60);

        C_Email.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_Email);
        C_Email.setBounds(180, 260, 320, 40);

        jLabel18.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel18.setText("Street");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 400, 140, 60);

        jLabel14.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel14.setText("State");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 500, 100, 60);

        C_PhoneNo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_PhoneNo);
        C_PhoneNo.setBounds(180, 360, 320, 40);

        C_Street.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_Street);
        C_Street.setBounds(180, 410, 320, 40);

        jLabel17.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel17.setText("Phone");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 350, 100, 60);

        jLabel15.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel15.setText("Area");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 450, 200, 60);

        C_Area.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_Area);
        C_Area.setBounds(180, 460, 320, 40);

        jLabel19.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel19.setText("City");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 560, 110, 60);

        jLabel20.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel20.setText("Password");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 300, 180, 60);

        C_State.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        C_State.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_StateMouseClicked(evt);
            }
        });
        jPanel1.add(C_State);
        C_State.setBounds(180, 520, 320, 30);

        C_City.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_City);
        C_City.setBounds(180, 570, 320, 30);

        C_Password.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(C_Password);
        C_Password.setBounds(180, 310, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_SignInActionPerformed
        // TODO add your handling code here:
        Cust_SignIn mf = new Cust_SignIn(conn);
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_Cust_SignInActionPerformed

    private void Cust_SignUp_Info_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_SignUp_Info_PageActionPerformed
        try {
            stmt = conn.prepareCall("{call signUpCustomer(?,?,?,?,?,?,?,?,?,?)}");
            stmt.setString(1, C_FName.getText());
            stmt.setString(2, C_LName.getText());
            stmt.setString(3, C_Street.getText());
            stmt.setString(4, C_Area.getText());
            stmt.setString(5, C_City.getSelectedItem().toString());
            stmt.setString(6, C_State.getSelectedItem().toString());
            stmt.setLong(7, Long.parseLong(C_PhoneNo.getText()));
            stmt.setString(8, C_Email.getText());
            stmt.setString(9, C_Password.getText());
            
            stmt.registerOutParameter(10, OracleTypes.INTEGER);
            stmt.execute();
            
            this.cusId = stmt.getInt(10);
            
            if(this.cusId != 0){
                showMessageDialog(null, "Signed UP Successfully! WELCOME :)");
                After_Cust_Sign_In_OR_Up mf1 = new After_Cust_Sign_In_OR_Up();
                this.setVisible(false);
                this.dispose();               
                mf1.setVisible(true);
            }
            else{
                showMessageDialog(null, "There was an ERROR :((", "ERROR", ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Cust_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Cust_SignUp_Info_PageActionPerformed

    private void C_StateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_StateMouseClicked
        // TODO add your handling code here:
        C_City.removeAllItems();
        try {
            stmt = conn.prepareCall("{call cityList(?, ?)}");
            stmt.setString(1, C_State.getSelectedItem().toString());
            
            stmt.registerOutParameter(2, OracleTypes.CURSOR);
            stmt.execute();

            rs = (ResultSet) stmt.getObject(2);
            while(rs.next()){
                C_City.addItem(rs.getString("c_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_C_StateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cust_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cust_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cust_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cust_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cust_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_Area;
    private javax.swing.JComboBox<String> C_City;
    private javax.swing.JTextField C_Email;
    private javax.swing.JTextField C_FName;
    private javax.swing.JTextField C_LName;
    private javax.swing.JPasswordField C_Password;
    private javax.swing.JTextField C_PhoneNo;
    private javax.swing.JComboBox<String> C_State;
    private javax.swing.JTextField C_Street;
    private javax.swing.JButton Cust_SignIn;
    private javax.swing.JButton Cust_SignUp_Info_Page;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
