/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

import javax.swing.ButtonGroup;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Harsh Kakasaniya
 */
public class DM_SignUp extends javax.swing.JFrame {

    Connection conn = null;
    CallableStatement stmt = null;
    ResultSet rs = null;
    int delGender = 1;
    int delId = 0;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    ArrayList<String> arL = new ArrayList<String>();
    
    public DM_SignUp() {
        initComponents();
        setSize(520,875);
        setTitle("Let's deliver FRESH FAST FOOD together !!!");
        
        ButtonGroup D = new ButtonGroup();
        D.add(Male);
        D.add(Female);
    }
    
    public DM_SignUp(Connection conn) {
        initComponents();
        setSize(520,875);
        setTitle("Let's deliver FRESH FAST FOOD together !!!");
        this.conn = conn;
        
        fillStates();
        
        ButtonGroup D = new ButtonGroup();
        D.add(Male);
        D.add(Female);
        Male.setSelected(true);
    }
    
    void fillStates(){
        try {
            stmt = conn.prepareCall("{call statesList(?)}");
            stmt.registerOutParameter(1, OracleTypes.CURSOR);
            stmt.execute();
            
            rs = (ResultSet) stmt.getObject(1);
            while(rs.next()){
                arL.add(rs.getString("s_code"));
                D_State.addItem(rs.getString("s_name"));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        D_SignUp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        D_Email = new javax.swing.JLabel();
        D_FName = new javax.swing.JTextField();
        D_LName = new javax.swing.JTextField();
        D_LiscenceNumber = new javax.swing.JTextField();
        D_PhoneNumber = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        D_EMail = new javax.swing.JTextField();
        BackToMain = new javax.swing.JButton();
        Female = new javax.swing.JRadioButton();
        D_City = new javax.swing.JComboBox();
        D_State = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        D_Password = new javax.swing.JPasswordField();
        birthDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 53)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("SignUp as Deliveryman");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 470, 70);

        D_SignUp.setBackground(new java.awt.Color(255, 153, 102));
        D_SignUp.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        D_SignUp.setText("Sign Up");
        D_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(D_SignUp);
        D_SignUp.setBounds(310, 730, 160, 70);

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel8.setText("First Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 110, 160, 60);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 160, 150, 60);

        jLabel11.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 210, 130, 60);

        jLabel13.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel13.setText("Phone No");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 310, 140, 60);

        jLabel15.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel15.setText("State");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 450, 80, 60);

        jLabel17.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel17.setText("Birthdate");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 360, 150, 60);

        jLabel18.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel18.setText("Liscence No");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 260, 180, 60);

        jLabel19.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel19.setText("City");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 500, 70, 60);

        D_Email.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        D_Email.setText("Email");
        jPanel1.add(D_Email);
        D_Email.setBounds(10, 590, 180, 60);

        D_FName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_FName);
        D_FName.setBounds(200, 120, 280, 40);

        D_LName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_LName);
        D_LName.setBounds(200, 170, 280, 40);

        D_LiscenceNumber.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_LiscenceNumber);
        D_LiscenceNumber.setBounds(200, 270, 280, 40);

        D_PhoneNumber.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_PhoneNumber);
        D_PhoneNumber.setBounds(200, 320, 280, 40);

        Male.setBackground(new java.awt.Color(255, 153, 102));
        Male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel1.add(Male);
        Male.setBounds(200, 220, 90, 40);

        D_EMail.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_EMail);
        D_EMail.setBounds(120, 600, 370, 40);

        BackToMain.setBackground(new java.awt.Color(255, 153, 102));
        BackToMain.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        BackToMain.setText("Back");
        BackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMainActionPerformed(evt);
            }
        });
        jPanel1.add(BackToMain);
        BackToMain.setBounds(40, 730, 160, 70);

        Female.setBackground(new java.awt.Color(255, 153, 102));
        Female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Female.setText("Female");
        Female.setAutoscrolls(true);
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        jPanel1.add(Female);
        Female.setBounds(310, 220, 100, 40);

        D_City.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        D_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_CityActionPerformed(evt);
            }
        });
        jPanel1.add(D_City);
        D_City.setBounds(120, 510, 360, 40);

        D_State.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        D_State.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_StateMouseClicked(evt);
            }
        });
        jPanel1.add(D_State);
        D_State.setBounds(120, 460, 360, 40);

        jLabel21.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel21.setText("Password");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 640, 180, 60);

        D_Password.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(D_Password);
        D_Password.setBounds(170, 650, 320, 40);

        birthDate.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(birthDate);
        birthDate.setBounds(200, 370, 280, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_SignUpActionPerformed
        try {
            // TODO add your handling code here:
            stmt = conn.prepareCall("{call signUpDel(?,?,?,?,?,?,?,?,?,?,?)}");
            stmt.setString(1, D_FName.getText());
            stmt.setString(2, D_LName.getText());
            stmt.setInt(3, this.delGender);
            stmt.setString(4, D_LiscenceNumber.getText());
            stmt.setLong(5, Long.parseLong(D_PhoneNumber.getText()));
            stmt.setString(6, sdf.format(birthDate.getDate()).toString());
            System.out.println(sdf.format(birthDate.getDate()));
            stmt.setString(7, arL.get(D_State.getSelectedIndex()));
            stmt.setString(8, D_City.getSelectedItem().toString());
            stmt.setString(9, D_EMail.getText());
            stmt.setString(10, D_Password.getText());
            
            stmt.registerOutParameter(11, OracleTypes.INTEGER);
            stmt.execute();
            
            this.delId = stmt.getInt(11);
            
            if(this.delId != 0){
                showMessageDialog(null, "Signed UP Successfully! WELCOME :)");
                PendingDelivery mf = new PendingDelivery();
                this.setVisible(false);
                this.dispose();
                mf.setVisible(true);                
            }
            else{
                showMessageDialog(null, "There was an ERROR :((", "ERROR", ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DM_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_D_SignUpActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
        this.delGender = 1;
    }//GEN-LAST:event_MaleActionPerformed

    private void BackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMainActionPerformed
        // TODO add your handling code here:
        Welcome mf = new Welcome();
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_BackToMainActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
        this.delGender = 0;
    }//GEN-LAST:event_FemaleActionPerformed

    private void D_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_CityActionPerformed

    private void D_StateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_StateMouseClicked
        // TODO add your handling code here:
        D_City.removeAllItems();
        try {
            stmt = conn.prepareCall("{call cityList(?, ?)}");
            stmt.setString(1, D_State.getSelectedItem().toString());
            //System.out.println(R_State.getSelectedItem().toString());
            stmt.registerOutParameter(2, OracleTypes.CURSOR);
            stmt.execute();
            
            rs = (ResultSet) stmt.getObject(2);
            while(rs.next()){
                D_City.addItem(rs.getString("c_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_D_StateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DM_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DM_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DM_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DM_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DM_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMain;
    private javax.swing.JComboBox D_City;
    private javax.swing.JTextField D_EMail;
    private javax.swing.JLabel D_Email;
    private javax.swing.JTextField D_FName;
    private javax.swing.JTextField D_LName;
    private javax.swing.JTextField D_LiscenceNumber;
    private javax.swing.JPasswordField D_Password;
    private javax.swing.JTextField D_PhoneNumber;
    private javax.swing.JButton D_SignUp;
    private javax.swing.JComboBox D_State;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private com.toedter.calendar.JDateChooser birthDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
