/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

import javax.swing.ButtonGroup;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleTypes;

import static javax.swing.JOptionPane.*;

/**
 *
 * @author Harsh Kakasaniya
 */
public class EditMenu extends javax.swing.JFrame {
    Connection conn = null;
    CallableStatement stmt = null;
    ResultSet rs = null;
    
    String resId = null;
    int typeOfOperation = 0;

    public EditMenu() {
        initComponents();
        setSize(630,500);
        setTitle("Edit your Menu !!!");
        
        ButtonGroup D = new ButtonGroup();
        D.add(Update);
        D.add(Delete);
        D.add(Add);
    }
    
    public EditMenu(String resId, Connection conn) {
        initComponents();
        setSize(630,500);
        setTitle("Edit your Menu !!!");
        this.conn = conn;
        this.resId = resId;
        
        ButtonGroup D = new ButtonGroup();
        D.add(Update);
        D.add(Delete);
        D.add(Add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NewItemName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NewPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NewQuantityPerServe = new javax.swing.JTextField();
        Update = new javax.swing.JRadioButton();
        Add = new javax.swing.JRadioButton();
        Delete = new javax.swing.JRadioButton();
        Edit_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 85)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Edit Your Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 580, 100);

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel8.setText("New Item ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 110, 150, 60);

        NewItemName.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(NewItemName);
        NewItemName.setBounds(170, 120, 410, 40);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel9.setText("Price (in Rs.)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 170, 190, 60);

        NewPrice.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(NewPrice);
        NewPrice.setBounds(230, 180, 350, 40);

        jLabel10.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel10.setText("Quantity/serve");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 230, 200, 60);

        NewQuantityPerServe.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(NewQuantityPerServe);
        NewQuantityPerServe.setBounds(230, 240, 350, 40);

        Update.setBackground(new java.awt.Color(255, 153, 102));
        Update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Update.setText("Update this info");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(40, 310, 140, 30);

        Add.setBackground(new java.awt.Color(255, 153, 102));
        Add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Add.setText("Add This Item");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(420, 310, 140, 30);

        Delete.setBackground(new java.awt.Color(255, 153, 102));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Delete.setText("Delete this item");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(230, 310, 140, 30);

        Edit_Menu.setBackground(new java.awt.Color(255, 153, 102));
        Edit_Menu.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Edit_Menu.setText("Edit Menu");
        Edit_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_Menu);
        Edit_Menu.setBounds(410, 360, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        this.typeOfOperation = 3;
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        this.typeOfOperation = 1;
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        this.typeOfOperation = 2;
    }//GEN-LAST:event_DeleteActionPerformed

    private void Edit_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_MenuActionPerformed
        // TODO add your handling code here:
        if(this.typeOfOperation == 0){
            showMessageDialog(null, "No Option Chosen!");
        }
        else{
            try {
            stmt = conn.prepareCall("{call editMenuDetails(?,?,?,?,?,?)}");
            stmt.setInt(1, this.typeOfOperation);
            stmt.setString(2, NewItemName.getText());
            stmt.setString(3, this.resId);
            stmt.setInt(4, Integer.parseInt(NewPrice.getText()));
            stmt.setString(5, NewQuantityPerServe.getText());
            System.out.println(resId + " ojbj");
            
            stmt.registerOutParameter(6, OracleTypes.INTEGER);
            stmt.execute();
            
            int success = stmt.getInt(6);
            
            if(success == 1){
                showMessageDialog(null, "Updated Successfully!");
            }
            else{
                showMessageDialog(null, "Error Occur while Updating :(", "Error",ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_Edit_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Add;
    private javax.swing.JRadioButton Delete;
    private javax.swing.JButton Edit_Menu;
    private javax.swing.JTextField NewItemName;
    private javax.swing.JTextField NewPrice;
    private javax.swing.JTextField NewQuantityPerServe;
    private javax.swing.JRadioButton Update;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
