/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

/**
 *
 * @author Harsh Kakasaniya
 */
public class PendingDelivery extends javax.swing.JFrame {

    /**
     * Creates new form PendingDelivery
     */
    public PendingDelivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveryPending = new javax.swing.JTextArea();
        DeliveriesPendingDropDown = new javax.swing.JComboBox();
        OrderDelievered = new javax.swing.JCheckBox();
        OrderPicked = new javax.swing.JCheckBox();
        UpdateDeliveries = new javax.swing.JButton();
        BackToMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 3, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Edit and Update your Pending Deliveries");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 1100, 100);

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel8.setText("Select the delivery you are working on");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 120, 510, 60);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel9.setText("Pending Dilevery List");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 120, 330, 60);

        DeliveryPending.setColumns(20);
        DeliveryPending.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        DeliveryPending.setRows(5);
        jScrollPane1.setViewportView(DeliveryPending);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 470, 430);

        DeliveriesPendingDropDown.setBackground(new java.awt.Color(255, 153, 102));
        DeliveriesPendingDropDown.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        DeliveriesPendingDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Need to set based on deliveries pending" }));
        DeliveriesPendingDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveriesPendingDropDownActionPerformed(evt);
            }
        });
        jPanel1.add(DeliveriesPendingDropDown);
        DeliveriesPendingDropDown.setBounds(560, 180, 530, 40);

        OrderDelievered.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        OrderDelievered.setText("Order Delivered");
        jPanel1.add(OrderDelievered);
        OrderDelievered.setBounds(890, 300, 200, 40);

        OrderPicked.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        OrderPicked.setText("Order Picked");
        jPanel1.add(OrderPicked);
        OrderPicked.setBounds(890, 260, 210, 40);

        UpdateDeliveries.setBackground(new java.awt.Color(255, 153, 102));
        UpdateDeliveries.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        UpdateDeliveries.setText("Update Dilevery Status");
        UpdateDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeliveriesActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDeliveries);
        UpdateDeliveries.setBounds(600, 550, 320, 60);

        BackToMainMenu.setBackground(new java.awt.Color(255, 153, 102));
        BackToMainMenu.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        BackToMainMenu.setText("Back");
        BackToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BackToMainMenu);
        BackToMainMenu.setBounds(960, 550, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveriesPendingDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveriesPendingDropDownActionPerformed
        // TODO add your handling code here:
        // ADD ITEMS BASED ON RESTAURANT SELECTED
    }//GEN-LAST:event_DeliveriesPendingDropDownActionPerformed

    private void UpdateDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeliveriesActionPerformed
        // TODO add your handling code here:
        // DEFINE WHAT TO DO HERE
    }//GEN-LAST:event_UpdateDeliveriesActionPerformed

    private void BackToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMainMenuActionPerformed
        // TODO add your handling code here:
        Welcome mf = new Welcome();
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_BackToMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingDelivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMainMenu;
    private javax.swing.JComboBox DeliveriesPendingDropDown;
    private javax.swing.JTextArea DeliveryPending;
    private javax.swing.JCheckBox OrderDelievered;
    private javax.swing.JCheckBox OrderPicked;
    private javax.swing.JButton UpdateDeliveries;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
