/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

/**
 *
 * @author Harsh Kakasaniya
 */
public class pendingOrders extends javax.swing.JFrame {

    /**
     * Creates new form pendingOrders
     */
    public pendingOrders() {
        initComponents();
        setSize(1150,680);
        setTitle("View and update your pending orders !!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDetails = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTextArea();
        Menu_Items_After_Sign_IN_OR_UP = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        UpdateDetails1 = new javax.swing.JButton();
        UpdateDetails2 = new javax.swing.JButton();

        UpdateDetails.setBackground(new java.awt.Color(255, 153, 102));
        UpdateDetails.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        UpdateDetails.setText("Update");
        UpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetailsActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Edit and Update your Pending Orders");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 1100, 100);

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel8.setText("Select the order you are working on");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(590, 120, 510, 60);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel9.setText("Pending Order List");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 120, 270, 60);

        Cart.setColumns(20);
        Cart.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Cart.setRows(5);
        jScrollPane1.setViewportView(Cart);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 470, 430);

        Menu_Items_After_Sign_IN_OR_UP.setBackground(new java.awt.Color(255, 153, 102));
        Menu_Items_After_Sign_IN_OR_UP.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Menu_Items_After_Sign_IN_OR_UP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Need to set based on orders pending" }));
        Menu_Items_After_Sign_IN_OR_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Items_After_Sign_IN_OR_UPActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Items_After_Sign_IN_OR_UP);
        Menu_Items_After_Sign_IN_OR_UP.setBounds(560, 180, 530, 40);

        jCheckBox1.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        jCheckBox1.setText("Order Ready");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(890, 300, 180, 40);

        jCheckBox2.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        jCheckBox2.setText("Order Received");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(890, 260, 210, 40);

        UpdateDetails1.setBackground(new java.awt.Color(255, 153, 102));
        UpdateDetails1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        UpdateDetails1.setText("Update Order Status");
        UpdateDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetails1ActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDetails1);
        UpdateDetails1.setBounds(620, 550, 300, 60);

        UpdateDetails2.setBackground(new java.awt.Color(255, 153, 102));
        UpdateDetails2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        UpdateDetails2.setText("Back");
        UpdateDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetails2ActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDetails2);
        UpdateDetails2.setBounds(960, 550, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Items_After_Sign_IN_OR_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Items_After_Sign_IN_OR_UPActionPerformed
        // TODO add your handling code here:
        // ADD ITEMS BASED ON RESTAURANT SELECTED
    }//GEN-LAST:event_Menu_Items_After_Sign_IN_OR_UPActionPerformed

    private void UpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDetailsActionPerformed
        // TODO add your handling code here:
        // DEFINE WHAT TO DO HERE
    }//GEN-LAST:event_UpdateDetailsActionPerformed

    private void UpdateDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDetails1ActionPerformed
        // TODO add your handling code here:
        // DEFINE WHAT TO DO HERE
    }//GEN-LAST:event_UpdateDetails1ActionPerformed

    private void UpdateDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDetails2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateDetails2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendingOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendingOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cart;
    private javax.swing.JComboBox Menu_Items_After_Sign_IN_OR_UP;
    private javax.swing.JButton UpdateDetails;
    private javax.swing.JButton UpdateDetails1;
    private javax.swing.JButton UpdateDetails2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
