/**
 *
 * @author Harsh Kakasaniya
 */
package dbms_project;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleTypes;

public class Rest_SignIn extends javax.swing.JFrame {
    Connection conn = null;
    CallableStatement stmt = null;
    ResultSet rs = null;
    
    public Rest_SignIn(){
        initComponents();
        setSize(520, 660);
        setTitle("Please verify your details !!!");
    }
    public Rest_SignIn(Connection conn) {
        initComponents();
        setSize(520,660);
        setTitle("Please verify your details !!!");
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Rest_Email = new javax.swing.JTextField();
        Rest_SignIn_Info_Page = new javax.swing.JButton();
        Rest_Pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 53)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("SignIn as Restaurant");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 440, 70);

        jLabel5.setFont(new java.awt.Font("Elephant", 3, 40)); // NOI18N
        jLabel5.setText("Restaurant Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 260, 410, 60);

        jLabel7.setFont(new java.awt.Font("Elephant", 3, 40)); // NOI18N
        jLabel7.setText("Restaurant Email");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 140, 400, 60);

        Rest_Email.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.add(Rest_Email);
        Rest_Email.setBounds(30, 200, 440, 40);

        Rest_SignIn_Info_Page.setBackground(new java.awt.Color(255, 153, 102));
        Rest_SignIn_Info_Page.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Rest_SignIn_Info_Page.setText("Sign In");
        Rest_SignIn_Info_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_SignIn_Info_PageActionPerformed(evt);
            }
        });
        jPanel1.add(Rest_SignIn_Info_Page);
        Rest_SignIn_Info_Page.setBounds(290, 410, 160, 70);

        Rest_Pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_PwdActionPerformed(evt);
            }
        });
        jPanel1.add(Rest_Pwd);
        Rest_Pwd.setBounds(40, 340, 430, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rest_SignIn_Info_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_SignIn_Info_PageActionPerformed
        try {
            // TODO add your handling code here:
            String resEmail = Rest_Email.getText();
            String resPwd = Rest_Pwd.getText();
            
            stmt = conn.prepareCall("{? = call signInRestaurant(?, ?)}");
            stmt.registerOutParameter(1, OracleTypes.CHAR);
            stmt.setString(2, resEmail);
            stmt.setString(3, resPwd);            
            stmt.execute();
            
            if(stmt.getString(1).equals("no_val")){
                System.out.println("Failed attempt to Sign-In");                 
            }
            else{
                After_Rest_Sign_In_OR_Up mf = new After_Rest_Sign_In_OR_Up(conn, stmt.getString(1));
                this.setVisible(false);
                this.dispose();
                mf.setVisible(true);
            }            
            
        } catch (SQLException ex) {
            Logger.getLogger(Rest_SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Rest_SignIn_Info_PageActionPerformed

    private void Rest_PwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_PwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rest_PwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rest_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rest_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rest_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rest_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rest_SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rest_Email;
    private javax.swing.JPasswordField Rest_Pwd;
    private javax.swing.JButton Rest_SignIn_Info_Page;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
