/**
 *
 * @author Harsh Kakasaniya
 */
package dbms_project;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.*;
import oracle.jdbc.OracleTypes;



import static java.lang.System.exit;


public class Welcome extends javax.swing.JFrame {

    Connection conn = null;
    
    public Welcome() {
        initComponents();
        setSize(1290,900);
        setTitle("Welcome to Fast Ordering System !!!");
        conn = DBConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Rest_SignIn = new javax.swing.JButton();
        Rest_SignUp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Deliveryman_SignUp = new javax.swing.JButton();
        Deliveryman_SignIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Continue_as_customer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 420, 430, 410);

        jLabel7.setFont(new java.awt.Font("Elephant", 3, 45)); // NOI18N
        jLabel7.setText("Are you ready ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, -10, 380, 120);

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel8.setText("to cook and serve ???");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 50, 380, 100);

        jLabel9.setFont(new java.awt.Font("Elephant", 3, 32)); // NOI18N
        jLabel9.setText("Apply as Restaurant");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 170, 390, 50);

        Rest_SignIn.setBackground(new java.awt.Color(255, 255, 255));
        Rest_SignIn.setFont(new java.awt.Font("Elephant", 3, 30)); // NOI18N
        Rest_SignIn.setText("Sign In");
        Rest_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_SignInActionPerformed(evt);
            }
        });
        jPanel2.add(Rest_SignIn);
        Rest_SignIn.setBounds(110, 240, 190, 60);

        Rest_SignUp.setBackground(new java.awt.Color(255, 255, 255));
        Rest_SignUp.setFont(new java.awt.Font("Elephant", 3, 30)); // NOI18N
        Rest_SignUp.setText("Sign Up");
        Rest_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_SignUpActionPerformed(evt);
            }
        });
        jPanel2.add(Rest_SignUp);
        Rest_SignUp.setBounds(110, 320, 190, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 420, 430, 410);

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 3, 380)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Welcome");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(-470, -420, 1270, 470);

        jLabel3.setFont(new java.awt.Font("Elephant", 3, 32)); // NOI18N
        jLabel3.setText("Apply as Deliveryman");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 170, 410, 50);

        jLabel5.setFont(new java.awt.Font("Elephant", 3, 45)); // NOI18N
        jLabel5.setText("Are you ready ");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(30, -10, 380, 120);

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel6.setText("to ride and serve ???");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 50, 380, 100);

        Deliveryman_SignUp.setBackground(new java.awt.Color(255, 255, 255));
        Deliveryman_SignUp.setFont(new java.awt.Font("Elephant", 3, 30)); // NOI18N
        Deliveryman_SignUp.setText("Sign Up");
        Deliveryman_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deliveryman_SignUpActionPerformed(evt);
            }
        });
        jPanel4.add(Deliveryman_SignUp);
        Deliveryman_SignUp.setBounds(110, 320, 190, 60);

        Deliveryman_SignIn.setBackground(new java.awt.Color(255, 255, 255));
        Deliveryman_SignIn.setFont(new java.awt.Font("Elephant", 3, 30)); // NOI18N
        Deliveryman_SignIn.setText("Sign In");
        Deliveryman_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deliveryman_SignInActionPerformed(evt);
            }
        });
        jPanel4.add(Deliveryman_SignIn);
        Deliveryman_SignIn.setBounds(110, 240, 190, 60);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(470, 420, 430, 410);

        jLabel2.setFont(new java.awt.Font("ITCEdwardianScriptW04-Reg", 3, 390)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Welcome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 1270, 400);

        Exit.setBackground(new java.awt.Color(255, 51, 51));
        Exit.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(1010, 760, 160, 50);

        Continue_as_customer.setBackground(new java.awt.Color(0, 204, 102));
        Continue_as_customer.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Continue_as_customer.setText("Continue as Customer");
        Continue_as_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue_as_customerActionPerformed(evt);
            }
        });
        jPanel1.add(Continue_as_customer);
        Continue_as_customer.setBounds(930, 670, 310, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void Deliveryman_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deliveryman_SignUpActionPerformed
        // TODO add your handling code here:
        DM_SignUp mf = new DM_SignUp(conn);
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_Deliveryman_SignUpActionPerformed

    private void Deliveryman_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deliveryman_SignInActionPerformed
        // TODO add your handling code here:
        DM_SignIn mf = new DM_SignIn(conn);
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_Deliveryman_SignInActionPerformed

    private void Rest_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_SignInActionPerformed
        // TODO add your handling code here:
        Rest_SignIn mf = new Rest_SignIn(conn);
        this.setVisible(false);
        this.dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_Rest_SignInActionPerformed

    private void Rest_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_SignUpActionPerformed
        // TODO add your handling code here:
        Rest_SignUp mf1 = new Rest_SignUp(conn);
        this.setVisible(false);
        this.dispose();
        mf1.setVisible(true);
    }//GEN-LAST:event_Rest_SignUpActionPerformed

    private void Continue_as_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue_as_customerActionPerformed
        // TODO add your handling code here:
        After_Continue_As_Customer mf2 = new After_Continue_As_Customer(conn);
        this.setVisible(false);
        this.dispose();
        mf2.setVisible(true);
    }//GEN-LAST:event_Continue_as_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue_as_customer;
    private javax.swing.JButton Deliveryman_SignIn;
    private javax.swing.JButton Deliveryman_SignUp;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Rest_SignIn;
    private javax.swing.JButton Rest_SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
